### ISSUE TITLE
pendingBalanceに1satoshiを割り込む小数点が含まれる場合に自動送金に失敗する

### ISSUE THREAD

**Issue by monochromegane** [campfire-inc/OKIMOCHI#15]
### 現象

1. okimochi registerでアドレスを登録
2. minimumTxAmountを超えるまでお気持ちをもらう

以上の条件を満たした際、お気持ちを表明した側に `RpcError: -3 Invalid amount` が届き、表明されたほうは、通常届く okimochi bot からのメッセージを受け取れず、かつ pendingBalanceも増加しない。

### 想像する原因

pendingBalanceが浮動小数点として扱っているため、`0.00030000000000000024 BTC` のように 1satoshi以下となる額を表現してしまっているようです。
これにより、 [sendToAddress時のamountToPay](https://github.com/campfire-inc/OKIMOCHI/blob/master/okimochi/index.js#L431)は絵文字に紐づくamountとpendingBalanceを足しこんだものですが、結果的に表現される額がBitcoin的に無効な値となっているのではないでしょうか。

なお、0.001などを指定した際のwithdraw(同じく[sendToAddressを使っている](https://github.com/campfire-inc/OKIMOCHI/blob/02fb16abdb56bde3cd3bac6e284e05e95b14ff31/okimochi/src/conversations.js#L33))は成功しました。

### 期待する結果

pendingBalanceの扱いを1satoshiを割り込まないようにした上で、自動送金が成功するようになってほしいです。

Nice product, thanks!

**Comment by joemphilips** [comment]
ありがとうございます。修正します。

**Comment by joemphilips** [comment]
#16 で修正したのでcloseします。まだ問題がありましたら再openしてください

**Comment by monochromegane** [comment]
ありがとうございます！
